AnimaApp/anima-dsa

- src/api/storybook.ts
- src/commands/sync.ts
- src/helpers/parse.ts
Check if the token is different, if he is different update it on the storybook.
https://app.asana.com/0/1203386270721893/1203384042838858/f
> feat(ds-token): update token if needed

- package.json
- src/api/storybook.ts
- src/cli.ts
- src/commands/sync.ts
- src/handleError.ts
- src/helpers/monitoring.ts
- yarn.lock
Add sentry tracing.
We can have the v2 of the tracing with a cleaner way like a plugin not impacting the code visibility and use a plugin way, mock import, or monkey patching.
> feat: sentry-tracing

- README.md
I've been through an update the `README.md` for the cli. We had some missing information and consistencies in wording. I think it reads better now.
I've also added some information about a bug we're aware of in Storybook and how to work around it.
This PR - https://github.com/AnimaApp/anima-design-to-code/pull/830 - makes a point of linking to this documentation which sparked the updating.
Asana task: https://app.asana.com/0/0/1203830048747724/f
> fix: update, reword and add to README.md.

- README.md
Add new logo with white background to account for dark mode and updated the TOC.
> fix: update logo and TOC.

- src/api/storybook.ts
- src/commands/status.ts
- src/commands/sync.ts
- src/helpers/waitAllProcessingStories.ts
> feat: check story processing before finishing

- src/commands/status.ts
- src/commands/sync.ts
- src/handleError.ts
- src/helpers/exit.ts
close sentry before exit enable us to send the error
> feat: clean sentry before exit

- src/cli.ts
- src/helpers/exit.ts
Adding catch for signal SIGINT, SIGTERM and SIGQUIT and cleaning Sentry before quitting.
> feat: catch termination signal and graceful shutdown

- README.md
> doc: add ips for animaapp api

- src/commands/sync.ts
We add the teamID in the user and as a tag.
Infos: a randome UID will be generated for the user if we add the team_id in the user.
> feat: add sentry user infos

- README.md
- src/api/storybook.ts
- src/commands/sync-design-tokens.ts
- src/helpers/file-system.ts
- src/helpers/hash.ts
https://www.loom.com/share/0fd7aee4ddaa40b08468c18e567d75fa
https://app.asana.com/0/1204315207094721/1204485586761684/f
> feature: sync design tokens only

- packages/anima-cli/src/commands/sync.ts
https://www.loom.com/share/c25a077160824c488f6e85d17773bf41
> improvement: don't wait for storybook processing when updating design tokens only

- packages/anima-cli/src/converters/tailwind.ts
- packages/framework-helpers/src/tailwind/tailwindTheme.ts
Defaulting to extends and not override default tailwind.
> fix: documentation for tailwind

- packages/docs/.vitepress/config.js
- packages/docs/guide/manage-design-tokens/design-tokens-css-variables.md
- packages/docs/guide/manage-design-tokens/design-tokens-tailwind.md
Change tailwind documentation for extend
> doc: change tailwind to extends

- packages/anima-cli/package.json
- packages/anima-cli/src/commands/sync.ts
- packages/anima-cli/src/helpers/analytics.ts
Add owner id to the the tracking
> chore(tracking): link to owner-id

- packages/docs/package.json
- pnpm-lock.yaml
Vue was not building without this dep
> fix(doc): build with vue

- packages/anima-cli/src/commands/sync.ts
- pnpm-lock.yaml
The owner is not set in mixpanel actually, we were using the wrong properties.
> fix: owner id for tracking in the CLI

- packages/anima-cli/src/helpers/analytics.ts
The ID was not sent to the body of the tracking..
> fix: tracking owner id

- packages/anima-cli/src/converters/antd.ts
- packages/framework-helpers/__tests__/antd.spec.ts
- packages/framework-helpers/src/antd/antdTheme.ts
- packages/framework-helpers/src/antd/types.ts
Description
Support number when extracting json for antd
> feat: number for antd

- packages/anima-cli/src/__tests__/antd.spec.ts
- packages/framework-helpers/__tests__/antd.spec.ts
- packages/framework-helpers/src/antd/antdTheme.ts
- packages/framework-helpers/src/antd/constants.ts
from "seed" to "antd" so that it doesnt generate confusion thinking that all tokens are Seed tokens.
> feat: change ant-d constant

- .changeset/chatty-yaks-give.md
- .gitignore
- packages/anima-cli/src/__tests__/antd.spec.ts
- packages/anima-cli/src/converters/antd.ts
- packages/framework-helpers/__tests__/antd.spec.ts
- packages/framework-helpers/src/antd/antdTheme.ts
- packages/framework-helpers/src/antd/types.ts
- pnpm-lock.yaml
Add support for other key than tokens with antd
> feat: antd json converter

- .changeset/chilly-shirts-reflect.md
- packages/framework-helpers/src/antd/antdTheme.ts
> fix: add dollar sign support for antd
